// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Verified against two real Vercel builds: DATABASE_URL (Neon's pooled
    // endpoint) applied `migrate deploy`'s advisory lock fine, while
    // DATABASE_URL_UNPOOLED (the direct endpoint) timed out waiting on that
    // same lock twice in a row — the opposite of the generic PgBouncer
    // advice, likely because the unpooled compute was cold/autosuspended
    // and didn't wake inside Prisma's fixed 10s lock-acquire window. Use the
    // pooled URL for both the CLI and lib/db.ts's app-runtime adapter.
    url: process.env["DATABASE_URL"],
    // `migrate dev` needs a scratch database for drift detection. Locally
    // this is `prisma dev`'s own shadow instance (see `npx prisma dev ls`);
    // in production `migrate deploy` never touches this (no shadow db
    // needed for deploy-only migrations), so this is dev-only.
    shadowDatabaseUrl: process.env["SHADOW_DATABASE_URL"],
  },
});
