// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // This installed Prisma version's config type has no `directUrl` field
    // (only `url`/`shadowDatabaseUrl`) — confirmed against
    // node_modules/@prisma/config/dist/index.d.ts, despite some docs
    // describing a newer/different API. Neon's pooled connection
    // (PgBouncer, transaction mode) doesn't support the session-level
    // advisory lock `migrate deploy` takes to guard against concurrent
    // migrations, so the *CLI's* datasource url prefers DATABASE_URL_UNPOOLED
    // (the name Vercel's Neon marketplace integration auto-provisions)
    // when set. lib/db.ts's app-runtime adapter reads DATABASE_URL (pooled)
    // independently, so this doesn't affect live request traffic. Locally
    // there's no pooler distinction (`prisma dev`), so this falls back to
    // DATABASE_URL when DATABASE_URL_UNPOOLED is unset.
    url: process.env["DATABASE_URL_UNPOOLED"] ?? process.env["DATABASE_URL"],
    // `migrate dev` needs a scratch database for drift detection. Locally
    // this is `prisma dev`'s own shadow instance (see `npx prisma dev ls`);
    // in production `migrate deploy` never touches this (no shadow db
    // needed for deploy-only migrations), so this is dev-only.
    shadowDatabaseUrl: process.env["SHADOW_DATABASE_URL"],
  },
});
